spring.main.show-banner: false
spring.jackson.serialization.INDENT_OUTPUT: true
management.context-path: /manage

error.whitelabel.enabled: false

spring.cache.type: infinispan
spring.cache.infinispan.config: infinispan.xml

logging.level.org.springframework: WARN
logging.level.org.hibernate: WARN
logging.level.org.elasticsearch: WARN
logging.level.io.undertow: WARN
logging.level.org.xnio: WARN
logging.level.io.mikael: DEBUG
